version: 0.2
phases: 
  install: 
    commands: 
      - apt-get update -y
      - apt-get install -y maven
  build: 
    commands: 
      - mvn clean package
      - docker image build -t thinknyx:app-b6 -d Dockerfile .
artifacts: 
  files: 
    - target/LiquorShop.war
    - CloudFormationCreateEC2.yml