AWSTemplateFormatVersion: '2010-09-09'
Description: This is our first template to create EC2 Server using CloudFormation

Parameters: 
  KeyName: 
    Description: Provide key pair that you would like to add to your EC2 to access it later
    Type: AWS::EC2::KeyPair::KeyName
  Source: 
    Description: Source IP Range for SSH
    Type: String
    MinLength: 9
    MaxLength: 18
Resources: 
  EC2Server: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-006493a8f627b96f9
      InstanceType: t2.micro
      KeyName: 
        Ref: KeyName
      SecurityGroups: 
        - Ref: SecurityGroup
  SecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Open for SSH
      SecurityGroupIngress: 
      - CidrIp: !Ref Source
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp